/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 11-ago.-2022 12:13:58 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Bicycle" CASCADE
;

DROP TABLE IF EXISTS checkin_logs CASCADE
;

DROP TABLE IF EXISTS parking CASCADE
;

DROP TABLE IF EXISTS "Usuario" CASCADE
;

/* Create Tables */

CREATE TABLE "Bicycle"
(
	bike_id smallint NOT NULL,
	color varchar(50) NOT NULL,
	description varchar(50) NOT NULL,
	brand varchar(50) NOT NULL,
	chasis_code varchar(50) NOT NULL,
	user_id integer NULL
)
;

CREATE TABLE checkin_logs
(
	log_id integer NOT NULL,
	bike_id smallint NOT NULL,
	event_type char(10) NOT NULL,
	user_id integer NOT NULL,
	parking_id smallint NULL,
	timestamp timestamp without time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE parking
(
	parking_id smallint NOT NULL,
	parking_name varchar(50) NOT NULL,
	parking_location varchar(50) NOT NULL
)
;

CREATE TABLE "Usuario"
(
	nombre varchar(50) NOT NULL,
	apellido varchar(50) NOT NULL,
	email varchar(320) NOT NULL,
	student_id numeric(11) NOT NULL,
	password varchar(50) NOT NULL,
	user_id integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Bicycle" ADD CONSTRAINT "PK_Bicycle"
	PRIMARY KEY (bike_id)
;

CREATE INDEX "IXFK_Bicycle_Usuario" ON "Bicycle" (user_id ASC)
;

ALTER TABLE checkin_logs ADD CONSTRAINT "PK_checkin_logs"
	PRIMARY KEY (log_id)
;

ALTER TABLE checkin_logs ADD CONSTRAINT "CK_event_type" CHECK (event_type IN('check in' ,'check out'))
;

CREATE INDEX "IXFK_checkin_logs_Bicycle" ON checkin_logs (bike_id ASC)
;

CREATE INDEX "IXFK_checkin_logs_Usuario" ON checkin_logs (user_id ASC)
;

ALTER TABLE parking ADD CONSTRAINT "PK_parking"
	PRIMARY KEY (parking_id)
;

ALTER TABLE "Usuario" ADD CONSTRAINT "PK_Usuario"
	PRIMARY KEY (user_id)
;

ALTER TABLE "Usuario" 
  ADD CONSTRAINT "UK_email" UNIQUE (email)
;

ALTER TABLE "Usuario" 
  ADD CONSTRAINT "UK_student_id" UNIQUE (student_id)
;

ALTER TABLE "Usuario" ADD CONSTRAINT "CK_email" CHECK (email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$')
;

CREATE INDEX "IX_email" ON "Usuario" (email ASC)
;

CREATE INDEX "IX_studentID" ON "Usuario" (student_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Bicycle" ADD CONSTRAINT "FK_Bicycle_Usuario"
	FOREIGN KEY (user_id) REFERENCES "Usuario" (user_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE checkin_logs ADD CONSTRAINT "FK_checkin_logs_Bicycle"
	FOREIGN KEY (bike_id) REFERENCES "Bicycle" (bike_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE checkin_logs ADD CONSTRAINT "FK_checkin_logs_parking"
	FOREIGN KEY (parking_id) REFERENCES parking (parking_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE checkin_logs ADD CONSTRAINT "FK_checkin_logs_Usuario"
	FOREIGN KEY (user_id) REFERENCES "Usuario" (user_id) ON DELETE No Action ON UPDATE No Action
;
